---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: ci
    groups:
      actions:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: build
