tap 'cloudfoundry/tap'
tap 'git-duet/tap'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/cask-versions'
tap 'minio/stable'
tap 'neovim/neovim'
tap 'universal-ctags/universal-ctags'
tap 'pivotal-cf/om'
tap 'zegervdv/zathura'

brew 'ack'
brew 'autoconf'
brew 'automake'
brew 'awscli'
brew 'bash'
brew 'bbl'
brew 'bosh-cli'
brew 'cabal-install'
brew 'cf-cli'
brew 'chruby'
brew 'cmake'
brew 'coreutils'
brew 'credhub-cli'
brew 'csvkit'
brew 'direnv'
brew 'docker'
brew 'erlang'
brew 'fontconfig'
brew 'freetype'
brew 'fzf'
brew 'gcc' # required by sbt
brew 'gd'
brew 'gdbm'
brew 'gettext'
brew 'gh'
brew 'ghc'
brew 'git'
brew 'git-crypt'
brew 'git-duet'
brew 'go'
brew 'gradle'
brew 'graphviz'
brew 'htop'
brew 'ipcalc'
brew 'jemalloc'
brew 'jmeter'
brew 'jq'
brew 'jpeg'
brew 'lastpass-cli'
brew 'leiningen'
brew 'libevent'
brew 'libpng'
brew 'libssh'
brew 'libtermkey'
brew 'libtiff'
brew 'libtool'
brew 'libuv'
brew 'libvterm'
brew 'libxml2'
brew 'libxslt'
brew 'libyaml'
brew 'lua'
brew 'mas'
brew 'minio'
brew 'om'
brew 'oniguruma'
brew 'openssl'
brew 'pivnet-cli'
brew 'pmd'
brew 'postgresql'
brew 'python'
brew 'python-yq'
brew 'maven'
brew 'mr'
brew 'msgpack'
brew 'neovim'
brew 'ngrep'
brew 'nmap'
brew 'node'
brew 'openldap'
brew 'rbenv'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'ripgrep'    # required by coc.nvim
brew 'ruby-install'
brew 's3cmd'
brew 'scala'
brew 'sbt'
brew 'telnet'
brew 'terraform'  # required by bbl
brew 'the_silver_searcher'
brew 'tig'
brew 'tmate'
brew 'tmux'
brew 'tree'
brew 'typescript'
brew 'universal-ctags', args: ['HEAD'] # requried by vim/tagbar
brew 'vim', args: ['with-lua']
brew 'watch'
brew 'webp'
brew 'wget'
brew 'wxmac'
brew 'yarn' # required by coc.vim
brew 'zsh'  # required by oh-my-zsh
brew 'zathura'  # required by coc-texlab
brew 'zathura-pdf-poppler'  # required by coc-texlab

cask 'android-platform-tools'
cask 'caffeine'
cask 'coconutbattery'
cask 'cozy-drive'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'flux'
cask 'fly'
cask 'flycut'
cask 'font-inconsolata'
cask 'google-chrome'
cask 'google-cloud-sdk'
cask 'google-drive-file-stream'
cask 'intellij-idea'
cask 'iterm2'
cask 'java'
cask 'java8'
cask 'keybase'
cask 'libreoffice'
cask 'mactex' # required by texlab
cask 'ngrok'
cask 'no-ip-duc'
cask 'prey'
cask 'protonmail-bridge'
cask 'slack'
cask 'shiftit'
cask 'skim' # required by coc-texlab
cask 'skype'
cask 'spotify'
cask 'thunderbird'
cask 'tor-browser'
cask 'tunnelblick'
cask 'vagrant'
#cask 'virtualbox'
#cask 'virtualbox-extension-pack'
cask 'vlc'
cask 'zoom'

mas 'Xcode', id: 497799835
