#tap 'carvel-dev/carvel'
#tap 'git-duet/tap'
#tap 'hashicorp/tap'
#tap 'heroku/brew'
#tap 'neovim/neovim'
#
#brew 'ack'
#brew 'autoconf'
#brew 'automake'
#brew 'awscli'
#brew 'azure-cli'
brew 'bash'
brew 'bash-language-server' # used by coc.nvim
brew 'bitwarden-cli'
brew 'block-goose-cli'
#brew 'cabal-install'
#brew 'chruby'
#brew 'cmake'
#brew 'coreutils'
#brew 'csvkit'
#brew 'direnv'
#brew 'erlang'
#brew 'fontconfig'
#brew 'freetype'
#brew 'fzf'
#brew 'gcc' # required by sbt
#brew 'gd'
#brew 'gdbm'
#brew 'gettext'
#brew 'gh'
#brew 'ghc'
brew 'git'
#brew 'git-crypt'
#brew 'git-duet'
brew 'go'
brew 'gopls'  # used by coc.nvim
#brew 'gradle'
#brew 'graphviz'
#brew 'gron'
#brew 'hashicorp/tap/terraform'  # required by bbl
#brew 'helm'
#brew 'heroku'
#brew 'htop'
#brew 'ipcalc'
#brew 'java' unless system "/usr/libexec/java_home --failfast"
#brew 'jemalloc'
#brew 'jmeter'
#brew 'jpeg'
brew 'jq'
#brew 'kapp'
#brew 'kbld'
#brew 'kind'
#brew 'leiningen'
#brew 'libevent'
#brew 'libpng'
#brew 'libssh'
#brew 'libtermkey'
#brew 'libtiff'
#brew 'libtool'
#brew 'libuv'
#brew 'libvterm'
#brew 'libxml2'
#brew 'libxslt'
#brew 'libyaml'
#brew 'lua'
#brew 'mas'
#brew 'maven'
#brew 'msgpack'
brew 'neovim'
#brew 'ngrep'
#brew 'nmap'
brew 'node'
#brew 'oniguruma'
#brew 'openldap'
#brew 'openssl'
#brew 'pmd'
#brew 'python'
#brew 'python-yq'
brew 'rbenv'
#brew 'readline'
#brew 'reattach-to-user-namespace' if OS.mac? # required by tmux plugin tmux-yank
#brew 'ripgrep'    # required by coc.nvim
#brew 'ruby-install'
#brew 's3cmd'
#brew 'sbt'
#brew 'scala'
#brew 'shellcheck' # used by vim in conjunction with bash-language-server
#brew 'telnet'
#brew 'the_silver_searcher'
brew 'tig'
#brew 'tmate'
brew 'tmux'
#brew 'tree'
#brew 'typescript'
brew 'universal-ctags', args: ['HEAD'] # requried by vim/tagbar
brew 'vim'
#brew 'watch'
#brew 'webp'
#brew 'wget'
brew 'xsel' if OS.linux? # required by tmux plugin tmux-yank
brew 'yarn' # required by coc.vim
#brew 'ytt'

#cask 'adobe-acrobat-reader'
#cask 'android-platform-tools'
#cask 'android-studio'
#cask 'caffeine' if OS.mac?
#cask 'docker-desktop'
#cask 'fly'
#cask 'flycut'
#cask 'gcloud-cli'
#cask 'iterm2' if OS.mac?
#cask 'libreoffice'
#cask 'nextcloud'
# cask 'thunderbird'
cask 'vlc'

#mas 'Xcode', id: 497799835

flatpak 'com.protonvpn.www'
flatpak 'com.slack.Slack'
flatpak 'com.spotify.Client'
flatpak 'org.mozilla.Thunderbird'
